services:
  - type: web
    name: dexcom-reader
    env: python
    region: oregon   # or choose your preferred region
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py  # adjust if your filename is different
    envVars:
      - key: Dexcom_username
        sync: false  # secure: Render will ask you to enter this value
      - key: Dexcom_password
        sync: false  # secure: same here
